branches/pre-alpha/src/milkshape/application/internals/survey/urls.py
from django.conf.urls.defaults import *
from django.views.generic.simple import direct_to_template

urlpatterns = patterns('survey.views',
    (r'^$', 'index', {'template_name': 'enquete.html'}),
    url(r'^thanks/$', direct_to_template, {'template': 'survey_thanks.html'}, name='survey_thanks'),
)

branches/pre-alpha/src/milkshape/urls.py
from django.conf.urls.defaults import *
from django.conf import settings

from django.views.generic.simple import direct_to_template

from django.contrib import admin
admin.autodiscover()

import os

from gateway import *

urlpatterns = patterns('',
    #url(r'^$', direct_to_template, {'template': 'homepage.html'}, name='home'),
    url(r'^gateway/$', gateway, name='gateway'),
    url(r'^home/$', direct_to_template, {'template': 'homepage.html'}, name='home'),
    (r'^about/', include('about.urls')),
    (r'^account/', include('account.urls')),
    (r'^issue/', include('issue.urls')),
    (r'^square/', include('square.urls')),
    (r'^profiles/', include('profiles.urls')),
    (r'^notices/', include('notification.urls')),
    (r'^survey/', include('survey.urls')),
    (r'^announcements/', include('announcements.urls')),
    (r'^admin/(.*)', admin.site.root),
)

if settings.DEBUG:
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT}),
    )

branches/pre-alpha/src/milkshape/application/internals/survey/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _

PROFESSION_CHOICES = (
    ('DA', 'Directeur Artistique'),
    ('Graphiste', 'Graphiste'),
    ('Illustrateur', 'Illustrateur'),
    ('MD', 'Motion designer'),
    ('Photographe', 'Photographe'),
    ('Etudiant', 'Etudiant'),
    ('Autre', 'Autre')
)

class Enquete(models.Model):
    coordonnees = models.CharField(_('Coordonnees'), max_length=255, null=False, blank=False)
    age = models.CharField(_('Age'), max_length=255, null=True, blank=True)
    email = models.EmailField(_('Mail'), max_length=255, null=False, blank=False)
    profession = models.CharField(_('Profession'), max_length=20, null=True, blank=True)
    place_to_work = models.CharField(_('Societe'), max_length=255, null=True, blank=True)
    
    question1 = models.TextField(_('Question_1'), null=True, blank=True)
    question2 = models.TextField(_('Question_2'), null=True, blank=True)
    question3 = models.TextField(_('Question_3'), null=True, blank=True)
    question4 = models.TextField(_('Question_4'), null=True, blank=True)
    question5 = models.TextField(_('Question_5'), null=True, blank=True)
    question6 = models.TextField(_('Question_6'), null=True, blank=True)
    question7 = models.TextField(_('Question_7'), null=True, blank=True)
    
    date_created = models.DateTimeField(_('creation_date'), auto_now_add=True)
    
    def __unicode__(self):
        return '%s - %s' % (self.coordonnees, self.email)

branches/pre-alpha/src/milkshape/application/internals/survey/forms.py
from django.forms import ModelForm
from survey.models import Enquete

class EnqueteForm(ModelForm):
    class Meta:
        model = Enquete
    def __init__(self, *args, **kwargs):
        super(EnqueteForm, self).__init__(*args, **kwargs)
        for i in range(7):
            self.fields['question%d' % (i + 1)].widget.attrs = {'rows': 5, 'cols': 53}

branches/pre-alpha/src/milkshape/application/internals/survey/views.py
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.template import RequestContext
from django.shortcuts import render_to_response

from survey.forms import EnqueteForm

def index(request, template_name, form_class=EnqueteForm):
    if request.method == 'POST':
        form = form_class(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('survey_thanks'))
    else:
        form = form_class()

    return render_to_response(template_name, {
        'form': form,
    }, context_instance=RequestContext(request))

branches/pre-alpha/src/milkshape/application/internals/survey/templates/base_questionnaire.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="fr" >

<head> 
    <title>{% block title %}{% endblock %}</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta name="language" content="fr" />
    <link rel="stylesheet" media="screen" type="text/css" title="index" href="{{ MEDIA_URL }}/css/style.css" />
    <script src="{{ MEDIA_URL }}/js/jquery-1.3.2.min.js" type="text/javascript"></script>
    <script src="{{ MEDIA_URL }}/js/core.js" type="text/javascript"></script>

</head>

<body>
	{% block questionnaire %}
	{% endblock %}
</body>
</html>

branches/pre-alpha/src/milkshape/application/internals/survey/templates/enquete.html
{% extends 'base_questionnaire.html' %}
{% load i18n %}

{% block title %}
Envies et motivations des cr&eacute;ateurs dans la cr&eacute;ation collaborative &gt; questionnaire
{% endblock %}

{% block questionnaire %}

{% get_current_language as LANGUAGE_CODE %}
{% get_available_languages as LANGUAGES %}
{% get_current_language_bidi as LANGUAGE_BIDI %}

<form action="/questionnaire/" method="POST">
    <h2 class="left">Vous ...</h2>
    {{ form.coordonnees.errors }}
    <p class="text">
        {{ form.coordonnees }}
        <label for="id_last_name">Nom / Pr&eacute;nom / Pseudonyme</label>
    </p>
    {{ form.age.errors }}
    <p class="text">
        {{ form.age }}
        <label for="id_age">{{ form.age.label_tag }}</label>
    </p>
    {{ form.profession.errors }}
    <p class="text">
        {{ form.profession }}
        <label for="id_profession">Profession</label>
    </p>
    {{ form.place_to_work.errors }}
    <p class="text">
        {{ form.place_to_work }}
        <label for="id_place_to_work">Soci&eacute;t&eacute; / &Eacute;cole</label>
    </p>
    {{ form.email.errors }}
    <p class="last text">{{ form.email }}<label for="email">Mail</label></p>
    
    <h2 class="right">... et l'art collaboratif</h2>
    {{ form.question1.errors }}
    <p>
        <label class="none" for="id_question1">{{ form.question1.label }}</label>
        {{ form.question1 }}
    </p>
    {{ form.question2.errors }}
    <p>
        <label class="none" for="id_question2">{{ form.question2.label }}</label>
        {{ form.question2 }}
    </p>
    {{ form.question3.errors }}
    <p>
        <label class="none" for="id_question3">{{ form.question3.label }}</label>
        {{ form.question3 }}
    </p>
    {{ form.question4.errors }}
    <p>
        <label class="none" for="id_question4">{{ form.question4.label }}</label>
        {{ form.question4 }}
    </p>
    {{ form.question5.errors }}
    <p>
        <label class="none" for="id_question5">{{ form.question5.label }}</label>
        {{ form.question5 }}
    </p>
    {{ form.question6.errors }}
    <p>
        <label class="none" for="id_question6">{{ form.question6.label }}</label>
        {{ form.question6 }}
    </p>
    {{ form.question7.errors }}
    <p>
        <label class="none" for="id_question7">{{ form.question7.label }}</label>
        {{ form.question7 }}
    </p>
	<p class="submit"><input type="submit" value="envoyer" /></p>
</form>
{% endblock %}

branches/pre-alpha/src/milkshape/application/internals/survey/templates/survey_thanks.html
{% extends 'base_questionnaire.html' %}

{% block title %}
Envies et motivations des cr&eacute;ateurs dans la cr&eacute;ation collaborative &gt; confirmation
{% endblock %}

{% block questionnaire %}
<h2 class="left">Merci d'avoir pris le temps de compl&egrave;ter notre questionnaire.</h2>
{% endblock %}